sudo: required
dist: xenial
language: generic
services:
  - docker
addons:
  apt:
    packages:
    - gearman-job-server
    - perl
    - perl-doc
    - cpanminus
    - libmodule-install-perl
    - libgearman-client-perl
    - libcrypt-rijndael-perl
    - libfile-slurp-perl
    - libtest-pod-coverage-perl
    - libtest-pod-perl
    - libtest-perl-critic-perl
before_install:
  - sudo apt-get update
  - cpanm -q -f --notest --no-man-pages Test::Vars

install:
  - perl Makefile.PL || exit 1

script:
  - sudo su $(id -un) -c 'eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib) && make test';
notifications:
  email:
    - sven@nierlein.de
